# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamERP_DEMO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TeamERP_DEMO

  target 'TeamERP_DEMOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TeamERP_DEMOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'DTTextField'
pod 'Tabman'
pod 'Alamofire'
pod 'MBProgressHUD'
pod 'PGTabBar'

end
